source 'https://rubygems.org'
gem 'rack', '~> 1.5'
gem 'thin'
gem 'sinatra', '~> 1.3'
gem 'sinatra-contrib'
gem 'sinatra-json'
gem 'sinatra-param'
gem 'sinatra-flash'	
gem 'sinatra-captcha'
gem 'haml'
gem 'sqlite3'
gem 'geoip'
gem 'jsobfu'
gem 'rack-throttle'
gem 'rack-attack'
gem 'unicode'
